### ISSUE TITLE
Erro ao instalar o projeto

### ISSUE THREAD

**Issue by lidymonteirowm** [thiagorossener/aloisioimoveis#1]
bom dia, tentei executar o passo a passo para instalação do projeto localmente mas está dando o seguinte erro ao executar o comando `python manage.py test`

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/lidiane/django/aloisioimoveis/aloisioimoveis/settings.py", line 26, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/decouple.py", line 77, in __call__
    return self.get(*args, **kwargs)
  File "/Users/lidiane/django/aloisioimoveis/.aloisioimoveis/lib/python3.5/site-packages/decouple.py", line 64, in get
    raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: SECRET_KEY option not found and default value was not defined.`

**Comment by felipealbuquerq** [comment]
Olá Lidy, 

para funcionar faça o seguinte na branch develop:

1. Adicione as seguintes chaves no .env (Não precisa por o valor, apenas as chaves)
GOOGLE_ANALYTICS_CODE=
GOOGLE_RECAPTCHA_SECRET_KEY=
GOOGLE_RECAPTCHA_SITE_KEY=

2. Após os testes que irão falhar, execute os seguintes comandos na sequência

python manage.py migrate --run-syncdb

python manage.py createsuperuser

python manage.py runserver

3. O acesso é em **/sistema** para cadastrar as informações que aparecerão no site
